"""empty message

Revision ID: 9bb57d73390a
Revises: b6d91bb0d5d0
Create Date: 2022-08-29 16:19:00.323217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb57d73390a'
down_revision = 'b6d91bb0d5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('ventas_productos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'ventas_productos')
    # ### end Alembic commands ###
